"""add_tier2_premium_models

Revision ID: 4838d1063301
Revises: 25bc34283f68
Create Date: 2026-08-26 20:37:32.898514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4838d1063301'
down_revision: Union[str, Sequence[str], None] = '25bc34283f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_reference',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mode', sa.Enum('kereta', 'mobil_pribadi', 'pesawat', 'travel', 'bis', name='transportmode'), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=False),
    sa.Column('destination_city', sa.String(length=255), nullable=False),
    sa.Column('estimated_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination_city', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('departure_month_target', sa.DateTime(), nullable=False),
    sa.Column('transport_mode', sa.Enum('kereta', 'mobil_pribadi', 'pesawat', 'travel', 'bis', name='transportmode'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_activities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('place_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_budget_summary',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_member', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_hotels',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('place_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('capacity_per_room', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_members',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='memberrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_vehicle_groups',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_installments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('month_index', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['trip_members.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_vehicle_members',
    sa.Column('group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['trip_vehicle_groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['trip_members.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('trip_vehicle_members')
    op.drop_table('trip_installments')
    op.drop_table('trip_vehicle_groups')
    op.drop_table('trip_members')
    op.drop_table('trip_hotels')
    op.drop_table('trip_budget_summary')
    op.drop_table('trip_activities')
    op.drop_table('trips')
    op.drop_table('price_reference')
    # ### end Alembic commands ###
