"""add_trip_transport

Revision ID: a935adbe0575
Revises: 4838d1063301
Create Date: 2026-08-26 20:56:05.891994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a935adbe0575'
down_revision: Union[str, Sequence[str], None] = '4838d1063301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_transport',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['trip_members.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_transport')
    # ### end Alembic commands ###
