"""add_total_cost_to_vehicle_groups

Revision ID: cfb301523ab3
Revises: a935adbe0575
Create Date: 2026-08-30 17:07:08.420296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb301523ab3'
down_revision: Union[str, Sequence[str], None] = 'a935adbe0575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_vehicle_groups', sa.Column('total_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_vehicle_groups', 'total_cost')
    # ### end Alembic commands ###
